name: Get First Author on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  get-first-author:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history including tags

      - name: Get First Author
        run: |
          git shortlog -n -s --since="7 days ago" | awk '{$1=""; sub(/^ /, ""); print $0}' | head -n 1
          FIRST_AUTHOR=$(git shortlog -n -s --since="7 days ago" | awk '{$1=""; sub(/^ /, ""); print $0}' | head -n 1)
          echo "First author in the last 7 days: $FIRST_AUTHOR"
