name: Super Linter

on:
  pull_request:
    branches: [ main ]

jobs:
  super-linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Super Linter
      uses: github/super-linter@v5
      env:
        VALIDATE_MARKDOWN: true  # Enable Markdown linting
        VALIDATE_DOCKERFILE: true  # Enable Dockerfile linting
        VALIDATE_ALL_CODEBASE: true  # Lint the entire codebase
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for permissions
        DISABLE_LINTERS: "CPP,PYTHON"  # Disable linting for other languages
