name: Super Linter

on:
  pull_request:
    branches: [ main ]

jobs:
  super-linter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run Super Linter
      uses: github/super-linter@v5
      env:
        VALIDATE_CPP: true  # Enable C++ linting (adjust other languages as needed)
        VALIDATE_PYTHON: true  # Enable Python linting
        VALIDATE_ALL_CODEBASE: true  # Lint the entire codebase
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for permissions
